- title: Barvení a úprava obočí, depilace
  description: Oživte svůj vzhled profesionálním barvením obočí a doplňte ho precizní depilací pro dokonalý look.

- title: Ošetření všech typů pleti
  description: Pro každý typ pleti nabízíme specifické ošetření, aby vaše pleť vždy zářila v nejlepším světle.

- title: Ošetření ultrazvukem
  description: Ultrazvukové ošetření pro hlubší regeneraci pleti. Obnovte svůj mladistvý vzhled s námi.

- title: Kosmetické masáže
  description: Dopřejte si chvíli relaxace a oživení pleti s našimi osvěžujícími kosmetickými masážemi.

- title: Lifting řas
  description: Máte rádi výrazné řasy? Naše procedura liftingu řas vám přinese pohled plný objemu.

- title: Enzymatický a chemický peeling
  description: Odstraňte odumřelé buňky a obnovte svou pleť s našimi efektivními peelingy.

- title: Intenzivní obličejové kúry
  description: Pro intenzivní péči nabízíme kúry, které vaší pleti dodají zářivost a vitalitu.

- title: Líčení
  description: Od přirozeného vzhledu po glam look - naše vizážistky vás promění podle vašeho přání.

- title: Suchá a mokrá pedikura
  description: Ať už preferujete suchou nebo mokrou pedikuru, vaše nohy budou v našich rukou vždy v dobré kondici.
